// Method to find ID of Data Feed Pair based on token address
const pairIDFinder = (fromToken, toToken) => {
    
}

// All Data Feeds supported by Tellor
const pairIDs = [
    { id: 1, pair: "ETH/USD" },
    { id: 2, pair: "BTC/USD" },
    { id: 3, pair: "BNB/USD" },
    { id: 4, pair: "BTC/USD" },
    { id: 5, pair: "ETH/BTC" },
    { id: 6, pair: "BNB/BTC" },
    { id: 7, pair: "BNB/ETH" },
    { id: 8, pair: "ETH/USD" },
    { id: 9, pair: "ETH/USD" },
    { id: 10, pair: "AMPL/USD" },
    { id: 11, pair: "ZEC/ETH" },
    { id: 12, pair: "TRX/ETH" },
    { id: 13, pair: "XRP/USD" },
    { id: 14, pair: "XMR/ETH" },
    { id: 15, pair: "ATOM/USD" },
    { id: 16, pair: "LTC/USD" },
    { id: 17, pair: "WAVES/BTC" },
    { id: 18, pair: "REP/BTC" },
    { id: 19, pair: "TUSD/ETH" },
    { id: 20, pair: "EOS/USD" },
    { id: 21, pair: "IOTA/USD" },
    { id: 22, pair: "ETC/USD" },
    { id: 23, pair: "ETH/PAX" },
    { id: 24, pair: "ETH/BTC" },
    { id: 25, pair: "USDC/USDT" },
    { id: 26, pair: "XTZ/USD" },
    { id: 27, pair: "LINK/USD" },
    { id: 28, pair: "ZRX/BNB" },
    { id: 29, pair: "ZEC/USD" },
    { id: 30, pair: "XAU/USD" },
    { id: 31, pair: "MATIC/USD" },
    { id: 32, pair: "BAT/USD" },
    { id: 33, pair: "ALGO/USD" },
    { id: 34, pair: "ZRX/USD" },
    { id: 35, pair: "COS/USD" },
    { id: 36, pair: "BCH/USD" },
    { id: 37, pair: "REP/USD" },
    { id: 38, pair: "GNO/USD" },
    { id: 39, pair: "DAI/USD" },
    { id: 40, pair: "STEEM/BTC" },
    { id: 41, pair: "USPCE" },
    { id: 42, pair: "BTC/USD" },
    { id: 43, pair: "TRB/ETH" },
    { id: 44, pair: "BTC/USD" },
    { id: 45, pair: "TRB/USD" },
    { id: 46, pair: "ETH/USD" },
    { id: 47, pair: "BSV/USD" },
    { id: 48, pair: "MAKER/USD" },
    { id: 49, pair: "BCH/USD" },
    { id: 50, pair: "TRB/USD" },
    { id: 51, pair: "XMR/USD" },
    { id: 52, pair: "XFT/USD" },
    { id: 53, pair: "BTCDOMINANCE" },
    { id: 54, pair: "WAVES/USD" },
    { id: 55, pair: "OGN/USD" },
    { id: 56, pair: "VIXEOD" },
    { id: 57, pair: "DEFITVL" },
    { id: 58, pair: "DEFIMCAP" },
    { id: 59, pair: "ETH/JPY" }
];

module.exports = { pairIDs, pairIDFinder };